### ISSUE TITLE
Header links in table of contents don't have "next section" links at the bottom

### ISSUE THREAD

**Issue by nelsonong** [IBMStreams/tutorials#19]
Header links like "Lab 1 - A Simple Streams Application" and "Reflections" which most people will probably click on don't have "next section" links at the bottom of the pages. Sub-links do.

**Comment by chanskw** [comment]
Thanks for the suggestion!

**Comment by markheger** [comment]
courses are gone: https://github.com/IBMStreams/tutorials/issues/57
