### ISSUE TITLE
Suggestions to streamline the  intro video 

### ISSUE THREAD

**Issue by jakrmpotic** [IBMStreams/tutorials#34]
The Streams course intro video runs  4.27 min and has this flow: 
•Explains what Streams is (2 min)
•Shows the Studio  and Console but  does not click through  their parts (Project Explorer, Streams Explorer in Studio)
•Lists the learning  objectives
•Shows links to related resources  (1 min)

I think the video could be enhanced to focus on answering these questions: 
•Why would I want to take this course?
•What will I get from this course?
•Anything I should know that will help me succeed in this course?

For example, consider these changes if you redo the video:
•Remove the first 2 min of conceptual info about Streams (Assume I know about Streams and that’s why I want to take this course.)
•Remove the last minute of related links, which I can’t click on. (Provide that type of info in the Lab HTML.)
•Start the video with the learning objectives. 
•Then give a quick tour of the Studio & Console, click through some of the key parts of the UI to introduce them and what I can do with them  (e.g., Project Explorer, Streams Explorer, palette, ...)  Such a tour would be helpful for newbies like me. I found that I stumbled on finding my way around the UI, and wasn't always sure when to switch contexts. Other things I would have liked to know - how frequently builds happen.

**Comment by markheger** [comment]
courses are gone: https://github.com/IBMStreams/tutorials/issues/57
