### ISSUE TITLE
VirtualBox instructions are incorrect 

### ISSUE THREAD

**Issue by jakrmpotic** [IBMStreams/tutorials#35]
The devWorks course material (including a video) says to download OVA files but none are available. 

When you update the devWorks content, update the instructions to correctly explain how to run the course on VirtualBox. 
FYI - Maybe reuse the correct instructions that I added to this content:
https://github.com/jakrmpotic/streamsx.documentation/blob/gh-pages/docs/4.2/qse-install-vm.markdown

**Comment by markheger** [comment]
courses are gone: https://github.com/IBMStreams/tutorials/issues/57
