### ISSUE TITLE
Step missing in Lab 2 in devWorks course

### ISSUE THREAD

**Issue by jakrmpotic** [IBMStreams/tutorials#36]
When I took the course on devWorks, I had a problem opening the instance graph in  2.3 “Monitor app by using the instance graph”.
I found the solution in the accompanying video: 
•First thing I have to do is go to Streams Explorer ->myinstance->show instance graph.
That step is missing from the Lab.

**Comment by markheger** [comment]
courses are gone: https://github.com/IBMStreams/tutorials/issues/57
