### ISSUE TITLE
Corrections to Lab 4 in devWorks course

### ISSUE THREAD

**Issue by jakrmpotic** [IBMStreams/tutorials#37]
Step 2.5.e: 
The Lab instructions don't match the accompanying video:
•Lab: Select the Import operator  and rename  it to Observations  by blanking out the alias.”
•Video: “Select the Import operator and rename it to FileImporter.

•Step 2.6.c: 
The lab instructions say to  launch the new application FileIngest. I couldn’t find an application to launch. I think a step is missing from the instructions. The solution is in the video: 
•Before I launch the application, I have to build the configuration in the Project Explorer.

**Comment by markheger** [comment]
courses are gone: https://github.com/IBMStreams/tutorials/issues/57
