### ISSUE TITLE
Python course should pull streamsx.health python module with a tag

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/tutorials#49]
The master branch of the toolkit is evolving.
To make sure that we do not break the course, the course should be updated to get the module from a release / tag.

@natashadsilva is this something we can work on together?

**Comment by natashadsilva** [comment]
@chanskw Sure, once you have a release for the module, let me know and I will update the links in the course notebooks. I don't think we need to update the course itself on developerWorks.

**Comment by EvanDimitriadis** [comment]
Hello and I apologize if that is not the correct thread.
While creating a notebook for the Steaming analytics in Python course I get this error after I run the command  :
`!pip install --upgrade "git+https://github.com/IBMStreams/streamsx.health#egg=streamsx_health.ingest&subdirectory=ingest/common/python/package"`

Collecting streamsx_health.ingest from git+https://github.com/IBMStreams/streamsx.health#egg=streamsx_health.ingest&subdirectory=ingest/common/python/package
  Cloning https://github.com/IBMStreams/streamsx.health to /tmp/s995-047b0d4ba154ea-255b410168f2/pip-build/streamsx-health.ingest
  Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/IBMStreams/streamsx.health /tmp/s995-047b0d4ba154ea-255b410168f2/pip-build/streamsx-health.ingest
Cannot find command 'git'

`!!which git`

['which: no git in (/usr/local/src/conda3_runtime.v24/4.1.1/bin:/usr/local/src/scala/2.10/bin:/usr/local/src/spark160master/ibm-java-x86_64-80/bin:/usr/local/src/bluemix_jupyter_bundle.v68/notebook/bin:/usr/local/src/bluemix_jupyter_bundle.v68/notebook/bin:/usr/local/src/bluemix_jupyter_bundle.v68/notebook/system/bin:/usr/local/src/bluemix_jupyter_bundle.v68/notebook/freetype/bin:/bin)']

Thank you in advance.

**Comment by chanskw** [comment]
Can you give me the link where you get this notebook from?  just so I know we are looking at teh same thing?

Are you running this in Data Science experience?  or you running in your own installation / environment?

**Comment by chanskw** [comment]
Looking at your error message, it looks like git is not installed in your environment and that's why you are running into this problem.

**Comment by EvanDimitriadis** [comment]
Yes, the course is https://developer.ibm.com/courses/all/streaming-analytics-basics-python-developers/.
And the link of the notebook is :
https://github.com/IBMStreams/tutorials/blob/master/OnlineCourse_IntroToPython/IntroToPython_exercise.ipynb

The thing is that I run this form the DSX as you posted. As far as I know, I cannot install git from the DSX console. That is why I included the !which git.

**Comment by natashadsilva** [comment]
Are you using DSX in the Cloud or the Desktop?

**Comment by natashadsilva** [comment]
Are you using DSX Cloud or DSX Desktop?

**Comment by EvanDimitriadis** [comment]
I am using DSX Cloud. I  run everything from the cloud.
 As I am a new user to your service maybe its my fault so maybe a picture from my browser could help.
![dsx](https://user-images.githubusercontent.com/33984704/33855243-0968b282-decd-11e7-87ba-bcf0dda70e74.jpg)

**Comment by natashadsilva** [comment]
Thanks for providing the screenshot. Problem seems to be specific to instances in the UK region. Support is working on it. Sorry about this.
In the meantime, could you please try  logging into https://datascience.ibm.com and creating the notebook there? 
And if you continue to have problems please post a question here: https://developer.ibm.com/answers/smart-spaces/22/streamsdev.html

**Comment by markheger** [comment]
no need to update the course and the notebook
